# Generated by Django 4.1.3 on 2022-12-02 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esports_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fav_color',
        ),
    ]
