# Generated by Django 4.1.3 on 2022-12-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports_app', '0004_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('icon', models.URLField()),
            ],
        ),
    ]
