# Generated by Django 4.1.3 on 2022-12-04 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports_app', '0008_match_score_match_team1_match_team2_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='users',
            field=models.ManyToManyField(related_name='matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
