# Generated by Django 4.1.3 on 2022-12-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports_app', '0011_alter_match_created_alter_match_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_damage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='total_deaths',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='total_eliminations',
            field=models.IntegerField(null=True),
        ),
    ]
