# Generated by Django 4.1.3 on 2022-12-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports_app', '0012_player_total_damage_player_total_deaths_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='hometown',
            field=models.CharField(max_length=25),
        ),
    ]
