# Generated by Django 4.1.3 on 2022-12-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports_app', '0013_alter_player_hometown'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.IntegerField(null=True),
        ),
    ]
