# Generated by Django 4.1.3 on 2022-12-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports_app', '0014_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='win',
            field=models.CharField(max_length=25),
        ),
    ]
