# Generated by Django 4.1.3 on 2022-12-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esports_app', '0015_alter_match_win'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
    ]
